# NumPy Arrays

In [1]:
my_lst = [1, 2, 3]

In [2]:
my_lst

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_lst)

In [6]:
arr

array([1, 2, 3])

In [7]:
mtx = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(mtx)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10, 2) # generate array

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.linspace(0, 5, 10) # create 10 evenly spaced points from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(4) # create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5) # create random numbers from 0 to 1 (uniform distribution)

array([0.02957635, 0.61763962, 0.67898025, 0.8430693 , 0.75348964])

In [ ]:
np.random.rand(5, 5)

array([[0.40863791, 0.59527532, 0.49951087, 0.79705636, 0.0053689 ],
       [0.82247384, 0.72128568, 0.93923613, 0.70434352, 0.66149124],
       [0.19168536, 0.96277965, 0.94150088, 0.94435247, 0.86353687],
       [0.04573047, 0.35047951, 0.01267676, 0.60898196, 0.08293454],
       [0.17897029, 0.23587739, 0.75058521, 0.86056015, 0.06083215]])

In [21]:
np.random.randn(5) # create random numbers from standard normal distribution centered around 0

array([ 0.60299096, -0.1417976 , -0.25554665, -1.21599679,  0.41177845])

In [22]:
np.random.randn(2, 3)

array([[-1.74618066,  0.21633958, -0.01983806],
       [ 1.55101475,  0.09696617,  0.09725767]])

In [ ]:
np.random.randint(1, 51, 5) # 5 random integers from 1 to 50

array([11,  9, 48, 15,  2], dtype=int32)

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0, 50, 10)

In [29]:
ranarr

array([21,  9,  3, 17, 33, 36, 24,  1, 41, 26], dtype=int32)

reshape will return an array containing the same data in the new shape

In [ ]:
arr.reshape(5, 5) # fill up or error

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max() # get max value

np.int32(41)

In [ ]:
ranarr.min() # get min value

np.int32(1)

In [ ]:
ranarr.argmax() # get the index of max value

np.int64(8)

In [35]:
ranarr.argmin() # get the index of min value

np.int64(7)

In [ ]:
arr.shape # get the shape (this one is 1 dimensional)

(25,)

In [38]:
arr = arr.reshape(5, 5)

In [ ]:
arr.shape # get the shape (this one is 2 dimensional)

(5, 5)

In [ ]:
arr.dtype # get datatype of array vals

dtype('int64')