# NumPy Arrays

In [1]:
lst = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
np.array(lst)

array([1, 2, 3])

In [4]:
mtx = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(mtx)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.88351924, 0.1773173 , 0.39528239, 0.86435733, 0.58080414])

In [15]:
np.random.rand(5, 5)

array([[0.98347938, 0.88289649, 0.38485193, 0.59255297, 0.32129806],
       [0.11088853, 0.96138008, 0.40001774, 0.52454962, 0.20105635],
       [0.85854284, 0.66510588, 0.50271758, 0.51280245, 0.11275472],
       [0.58329101, 0.4668932 , 0.5250135 , 0.29209504, 0.16175878],
       [0.60192817, 0.56850423, 0.33505678, 0.59005811, 0.96345093]])

In [16]:
np.random.randn(4, 4)

array([[-1.5690343 ,  2.20535181, -0.37162671, -1.05703191],
       [ 0.56075095,  1.35954718, -0.79791156, -1.27861033],
       [ 0.53455997,  1.28671833,  1.31509826, -0.1483738 ],
       [ 1.00605132, -0.56625978, -0.18647142,  0.38761679]])

In [17]:
np.random.randint(1, 100)

42

In [18]:
np.random.randint(1, 100, 10)

array([76, 76,  7, 35, 15, 88, 97,  4, 75, 24], dtype=int32)

In [19]:
arr = np.arange(25)

In [20]:
ranarr = np.random.randint(0, 50, 10)

In [21]:
ranarr

array([43, 21,  7,  5, 20, 18, 24, 27,  8, 34], dtype=int32)

In [22]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
ranarr.max()

np.int32(43)

In [24]:
ranarr.min()

np.int32(5)

In [25]:
ranarr

array([43, 21,  7,  5, 20, 18, 24, 27,  8, 34], dtype=int32)

In [26]:
ranarr.argmax()

np.int64(0)

In [27]:
ranarr.argmin()

np.int64(3)

In [28]:
arr.shape

(25,)

In [29]:
newarr = arr.reshape(5, 5)

In [30]:
newarr.shape

(5, 5)

In [31]:
arr.dtype

dtype('int64')