# NumPy Arrays

In [1]:
my_lst = [5, 1, 4, 2, 3]

In [2]:
my_lst # python list

[5, 1, 4, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_lst)

In [5]:
arr # numpy array (ndarray)

array([5, 1, 4, 2, 3])

In [6]:
print(type(my_lst), type(arr))

<class 'list'> <class 'numpy.ndarray'>


In [7]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0, 10, 6) # six numbers evenly spaced from 0 to 10

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
np.eye(4) # identity matrix (diagonally ones)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random numbers (commonly used when dealing with ml)

In [20]:
np.random.rand(5)

array([0.20877613, 0.5907045 , 0.27442039, 0.36621112, 0.58106413])

In [21]:
np.random.rand(5, 5)

array([[0.2649519 , 0.67623545, 0.72299077, 0.16662307, 0.75283412],
       [0.00118019, 0.44704174, 0.23487801, 0.02946126, 0.45636044],
       [0.60377538, 0.82233494, 0.06427968, 0.88165049, 0.87308471],
       [0.61800994, 0.62246977, 0.54286639, 0.40047474, 0.12973581],
       [0.49204575, 0.88404398, 0.23741071, 0.25671759, 0.12069795]])

In [ ]:
np.random.randn(2) # random standard normal distribution centered around 0

array([0.38878377, 1.07299831])

In [23]:
np.random.randn(4,4)

array([[-0.32113327, -0.75140804, -0.4637608 , -0.29625518],
       [ 0.20952216, -1.37850064, -0.92964959,  0.73328463],
       [ 1.54276257,  0.94855771, -1.16502141, -0.28721598],
       [ 0.01804706, -0.11681831,  0.27671457, -1.43910667]])