# Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[7]

np.int64(7)

In [5]:
arr[2:6]

array([2, 3, 4, 5])

In [6]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[1:5] = 100 # broadcasting array

In [9]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0, 11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:6] # data isn't copied, just a view of arr

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] = 99 # this is also gonna change in the original arr

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr # this is 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy() # copies the arr instead of just the view of it

In [18]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[0:3] = 100

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy

array([100, 100, 100,  99,  99,  99,   6,   7,   8,   9,  10])

In [23]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[0]

array([ 5, 10, 15])

In [28]:
arr_2d[2][1]

np.int64(40)

In [29]:
arr_2d[2,1]

np.int64(40)

In [30]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
arr = np.arange(1, 11)

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
bool_arr = arr > 5

In [35]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [36]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [37]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [38]:
arr[arr<3]

array([1, 2])

In [39]:
arr_2d = np.arange(50).reshape(5,10)

In [40]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])