# Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

np.int64(8)

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5] = 100

In [7]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0, 11)

In [9]:
slice_of_arr = arr[0:6]

In [10]:
slice_of_arr[:] = 99

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
arr_cpy = arr.copy()

In [13]:
arr[:] = 100

In [14]:
arr_cpy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
arr_2d = np.array([[5, 1, 4], [2, 3, 6], [8, 7, 9]])

In [17]:
arr_2d

array([[5, 1, 4],
       [2, 3, 6],
       [8, 7, 9]])

In [18]:
arr_2d[0]

array([5, 1, 4])

In [19]:
arr_2d[1, 1]

np.int64(3)

In [20]:
arr_2d[:2, 1:]

array([[1, 4],
       [3, 6]])

In [21]:
arr = np.arange(1, 11)

In [22]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [23]:
bool_arr = arr > 5

In [24]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [25]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [26]:
arr[arr<3]

array([1, 2])